# https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: containerversions.custom.k8s.io
spec:
  group: custom.k8s.io
  version: v1
  scope: Namespaced
  names:
    plural: containerversions
#    singular: containerversion
    kind: ContainerVersion
#    listKind: ContainerVersionList
    shortNames:
    - cv
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required:
            - tag
            - imageRepo
            - selector
            - container
          properties:
            tag:
              type: string
              pattern: '^[a-zA-Z0-9-_.]*$'
            versionSyntax:
              type: string
              ## default to regex for sha
              # default: '[0-9a-f]{5,40}'
            imageRepo:
              type: string
              pattern: '^[^:]*$'
            # selector:
            #   type: objects
            selector:
              properties:
                cvapp:
                  type: string
              required:
                - cvapp
              # type: object
              # See https://github.com/kubernetes/kubernetes/issues/59485 maps not supported fully
              # additionalProperties:
              #   type: string
              # # This would work .. map should only be keyed on string type
              # # so not using it
              # additionalProperties: true
            container:
              name:
                type: string
              verify:
                type: array
                kind:
                  type: string
                image:
                  type: string
                  pattern: '^[^:]*$'
              required:
                - name
            pollIntervalSeconds:
              type: integer
            livenessSeconds:
              type: integer
            config:
              name:
                type: string
              key:
                type: string
            strategy:
              kind:
                type: string
              blueGreen:
                serviceName:
                  type: string
                verificationServiceName:
                  type: string
                labelNames:
                  type: array
                  items:
                    type: string
                scaleDown:
                  type: boolean
              verify:
                type: array
                kind:
                  type: string
                image:
                  type: string
                  pattern: '^[^:]*$'
