{{- if .Values.autoUpdateCVM -}}
kind: ContainerVersion
apiVersion: custom.k8s.io/v1
metadata:
  name: {{ template "cvmanager.fullname" . }}-cv
  namespace: {{ .Release.Namespace }}
spec:
  imageRepo: "{{ .Values.image.repository }}"
  tag: {{ .Values.cvCD.refTag }}
  pollIntervalSeconds: {{ .Values.cvCD.frequecy }}
{{- with .Values.cvCD.selector }}
  selector:
{{ toYaml . | indent 4 }}
{{- end }}
  container:
    name: {{ .Chart.Name }}
  config:
    name: {{ template "cvmanager.fullname" . }}
    key: version
{{- end }}
