apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: containerversions.custom.k8s.io
  annotations:
    "helm.sh/hook": post-delete
spec:
  group: custom.k8s.io
  version: v1
  scope: Namespaced
  names:
    plural: containerversions
#    singular: containerversion
    kind: ContainerVersion
#    listKind: ContainerVersionList
    shortNames:
    - cv
