{{- if .Values.autoUpdateKCD -}}
kind: KCD
apiVersion: custom.k8s.io/v1
metadata:
  name: {{ template "kcd.fullname" . }}-kcd
  namespace: {{ .Release.Namespace }}
spec:
  imageRepo: "{{ .Values.image.repository }}"
  tag: {{ .Values.kcdCD.refTag }}
  pollIntervalSeconds: {{ .Values.kcdCD.frequecy }}
{{- with .Values.kcdCD.selector }}
  selector:
{{ toYaml . | indent 4 }}
{{- end }}
  container:
    name: {{ .Chart.Name }}
  config:
    name: {{ template "kcd.fullname" . }}
    key: version
{{- end }}
