kind: "Template"
apiVersion: "v1"
metadata:
  name: "cvmanager-template"
  annotations:
    description: "Template for cvmanager service"
labels:
  template: "cvmanager-template"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: cvmanagerapp
      namespace: kube-system
      labels:
        app: cvmanager
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: cvmanager
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
      minReadySeconds: 30
      template:
        metadata:
          labels:
            app: cvmanager
            component: cvmanagerapp
        spec:
          nodeSelector:
            node-role.kubernetes.io/master: ""
          tolerations:
            - key: "node-role.kubernetes.io/master"
              effect: NoSchedule
          containers:
            - name: cvmanagerapp-container
              image: $(REPOSITORY):$(VERSION)
              imagePullPolicy: Always
              ports:
                - name: http
                  protocol: TCP
                  containerPort: 8081
              args:
                - "run"
                - "--configmap-key=kube-system/cvmanager"
                - "--history=$(USE_HISTORY)"
                - "--cv-img-repo=$(REPOSITORY)"
              env:
              - name: NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: STATS_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              livenessProbe:
                httpGet:
                  path: /alive
                  port: http
              readinessProbe:
                httpGet:
                  path: /alive
                  port: http
  - kind: Service
    apiVersion: v1
    metadata:
      name: cvmanagerapp
      namespace: kube-system
      labels:
        app: cvmanager
    spec:
      type: NodePort
      ports:
        - port: 80
          targetPort: http
          protocol: TCP
          name: http
      selector:
        app: cvmanager
  - kind: ContainerVersion
    apiVersion: custom.k8s.io/v1
    metadata:
      name: cvmanager-cv
      namespace: kube-system
    spec:
      imageRepo: $(REPOSITORY)
      tag: $(VERSION)
      checkFrequency: 5
      selector:
        cvapp: cvmanagercv
      container: cvmanagerapp-container
      config:
        name: cvmanager
        key: version
  - kind: ConfigMap
    apiVersion: v1
    data:
      version: $(VERSION)
    metadata:
      name: cvmanager
      namespace: kube-system
parameters:
  - name: "VERSION"
    description: "version of the application for deployment"
    required: true
    parameterType: "string"
    value: "latest"
  - name: "REPOSITORY"
    description: "repository to pull image from"
    required: true
    parameterType: "string"
    value: "nearmap/cvmanager"
  - name: "USE_HISTORY"
    description: "version of the application for deployment"
    required: true
    value: true
    parameterType: "bool"
