# https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kcds.custom.k8s.io
spec:
  group: custom.k8s.io
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  scope: Namespaced
  names:
    plural: kcds
#    singular: kcd
    kind: KCD
#    listKind: KCDList
    shortNames:
    - kcd
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required:
            - tag
            - imageRepo
            - selector
            - container
          properties:
            tag:
              type: string
              pattern: '^[a-zA-Z0-9-_.]*$'
            versionSyntax:
              type: string
              ## default to regex for sha
              # default: '[0-9a-f]{5,40}'
            imageRepo:
              type: string
              pattern: '^[^:]*$'
            # selector:
            #   type: objects
            selector:
              properties:
                kcdapp:
                  type: string
              required:
                - kcdapp
              # type: object
              # See https://github.com/kubernetes/kubernetes/issues/59485 maps not supported fully
              # additionalProperties:
              #   type: string
              # # This would work .. map should only be keyed on string type
              # # so not using it
              # additionalProperties: true
            container:
              properties:
                name:
                  type: string
                verify:
                  type: array
                  items:
                    kind:
                      type: string
                    image:
                      type: string
                      pattern: '^[^:]*$'
              required:
                - name
            pollIntervalSeconds:
              type: integer
            livenessSeconds:
              type: integer
            config:
              properties:
                name:
                  type: string
                key:
                  type: string
            strategy:
              properties:
                kind:
                  type: string
                blueGreen:
                  properties:
                    serviceName:
                      type: string
                    verificationServiceName:
                      type: string
                    labelNames:
                      type: array
                      items:
                        type: string
                    scaleDown:
                      type: boolean
                verify:
                  type: array
                  items:
                    kind:
                      type: string
                    image:
                      type: string
                      pattern: '^[^:]*$'
