# https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: containerversions.custom.k8s.io
spec:
  group: custom.k8s.io
  version: v1
  scope: Namespaced
  names:
    plural: containerversions
#    singular: containerversion
    kind: ContainerVersion
#    listKind: ContainerVersionList
    shortNames:
    - cv
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            tag:
              type: string
              pattern: '^[a-zA-Z0-9-_.]*$'
            imageRepo:
              type: string
              pattern: '^[^:]*$'
            ## Would be better to use label selector but this will be done later
            ## Simple for now
            deployment:
              name:
                type: string
              container:
                type: string
            checkFrequency:
              ## frequency in minutes
              type: integer
            config:
              name:
                type: string
              key:
                type: string
