/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	custom_v1 "github.com/nearmap/kcd/gok8s/apis/custom/v1"
	versioned "github.com/nearmap/kcd/gok8s/client/clientset/versioned"
	internalinterfaces "github.com/nearmap/kcd/gok8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/nearmap/kcd/gok8s/client/listers/custom/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ContainerVersionInformer provides access to a shared informer and lister for
// ContainerVersions.
type ContainerVersionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ContainerVersionLister
}

type containerVersionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewContainerVersionInformer constructs a new informer for ContainerVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewContainerVersionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredContainerVersionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredContainerVersionInformer constructs a new informer for ContainerVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredContainerVersionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CustomV1().ContainerVersions(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CustomV1().ContainerVersions(namespace).Watch(options)
			},
		},
		&custom_v1.ContainerVersion{},
		resyncPeriod,
		indexers,
	)
}

func (f *containerVersionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredContainerVersionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *containerVersionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&custom_v1.ContainerVersion{}, f.defaultInformer)
}

func (f *containerVersionInformer) Lister() v1.ContainerVersionLister {
	return v1.NewContainerVersionLister(f.Informer().GetIndexer())
}
