/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	custom_v1 "github.com/wish/kcd/gok8s/apis/custom/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKCDs implements KCDInterface
type FakeKCDs struct {
	Fake *FakeCustomV1
	ns   string
}

var kcdsResource = schema.GroupVersionResource{Group: "custom.k8s.io", Version: "v1", Resource: "kcds"}

var kcdsKind = schema.GroupVersionKind{Group: "custom.k8s.io", Version: "v1", Kind: "KCD"}

// Get takes name of the kCD, and returns the corresponding kCD object, and an error if there is any.
func (c *FakeKCDs) Get(name string, options v1.GetOptions) (result *custom_v1.KCD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kcdsResource, c.ns, name), &custom_v1.KCD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*custom_v1.KCD), err
}

// List takes label and field selectors, and returns the list of KCDs that match those selectors.
func (c *FakeKCDs) List(opts v1.ListOptions) (result *custom_v1.KCDList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kcdsResource, kcdsKind, c.ns, opts), &custom_v1.KCDList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &custom_v1.KCDList{}
	for _, item := range obj.(*custom_v1.KCDList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kCDs.
func (c *FakeKCDs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kcdsResource, c.ns, opts))

}

// Create takes the representation of a kCD and creates it.  Returns the server's representation of the kCD, and an error, if there is any.
func (c *FakeKCDs) Create(kCD *custom_v1.KCD) (result *custom_v1.KCD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kcdsResource, c.ns, kCD), &custom_v1.KCD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*custom_v1.KCD), err
}

// Update takes the representation of a kCD and updates it. Returns the server's representation of the kCD, and an error, if there is any.
func (c *FakeKCDs) Update(kCD *custom_v1.KCD) (result *custom_v1.KCD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kcdsResource, c.ns, kCD), &custom_v1.KCD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*custom_v1.KCD), err
}

// Delete takes name of the kCD and deletes it. Returns an error if one occurs.
func (c *FakeKCDs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kcdsResource, c.ns, name), &custom_v1.KCD{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKCDs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kcdsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &custom_v1.KCDList{})
	return err
}

// Patch applies the patch and returns the patched kCD.
func (c *FakeKCDs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *custom_v1.KCD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kcdsResource, c.ns, name, data, subresources...), &custom_v1.KCD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*custom_v1.KCD), err
}
